import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import styles from '../styles/Home.module.css';
import { Tabs, Box } from '@mui/material';
import { useRouter } from 'next/router';
import Login from './login';
import { useEffect } from 'react';

export default function Home() {
  // const router = useRouter();
  
  // console.log(router.pathname);

  //if(router.pathname==="/" || router.pathname==="/login") return <Login/>;

  return (
    <div>
      <Login></Login>
    </div>
    // <div className={styles.container}>
    //   <Head>
    //     <title>Create Next App</title>
    //     <meta name="description" content="Generated by create next app" />
    //     <link rel="icon" href="/favicon.ico" />
    //   </Head>
    // </div>
  )
}
